version: '3.9'

services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER:?}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
            - POSTGRES_DB=${POSTGRES_DB:?}
        volumes:
            - 'postgres:/var/lib/postgresql/data'
    postgres-test:
        image: postgres
        ports:
            - '5433:5432'
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${TEST_POSTGRES_USER:?}
            - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD:?}
            - POSTGRES_DB=${TEST_POSTGRES_DB:?}
        volumes:
            - 'postgres:/var/lib/postgresql/test-data'

volumes:
    postgres:
    postgres-test: